@host = https://localhost
@port = 7149
@Restaurants.API_HostAddress = https://localhost:7149
@token = CfDJ8DFRKF6ibBBCqWm4AJ29De9H9QDThl4VIQZ_oX_1PlMneVLcHZvIGuHEsihPe77bHwxFwCDzu8HdKkYoEXDVTpRuij6NbNnmHJY3amWfXIzj1w198vT6tZ4XntIuAbQQYp1_a-Nnxi7BFcE1o2pRi4Jx1AT1zPLWy0gCS5L_R2-9cZhSRAxnaPK5FjAWWchgDdB8mAQnJoyLeTntCrTlQsrbTpQa727OxOGG_rArFhBpwvs-7g7R-uHQaLKjwtjkP6mD55GuJd4tyGmWbywZC162mM_BKyzQUDNRhQwn9JcelZaHymMTU1XSnteLc5_T4A41cke9j8BDDZwMXX5hBo1m34xwZrB6czxTMi7VP5C8A33t1aNwg11vtAZu2MMgyvmcvndNFufgzcEDCCsdClEgMjO4C5-lWih_qqTxyURwD_tlThwO-hX_VsIuSF4i1mUhSy8rCNZXTYaGLjXwV6RguzwMOMjIKrJsD8SXQiay3l2JX-QyiDbn4Ef90D9axbVg_Cpxdr-VWpi2W0LHAftmvTXz0GjKrG6YtkWH_HDBxv6MZeQgOBhBHCM_MxF4ZNFjz_Ls-x7FcwDqyJKeSLY2D7IdUskc-C-OSuGtE6ek8X9XI2IVxahieRNvDCxW8x2gkYx-sQ3j9HhxBnIgac0OdfxLobXonoQVIlToIiWv-6H1y9FDPOQjcuzZueIs8OmV2_fG97IIBm9Yv3IwWW7ezXZjMbOKvRWsG3mwuBuVadn-GkIGAwSFKXJ7rOWVQjG2YZGLXX0TpcvJqH-49IVdT6AI4X-IiqdZ7NPJSqAH9cJHhP4VDyryqUW3ThKTrFOtP2RvgH3-zzaGnRjl5POKc7d3TWJ2yNSoyGpmqCsw
@tokenOwner = CfDJ8DFRKF6ibBBCqWm4AJ29De9aHXyKD-gcdF34eq6L502MTpxwfwsdoi6b6poquaLXGN7RfuF6utAZGAf11BpQcamx53W7Rv6o-E3E__6K-J9qJHmgmr7YbyX1NvSUMVIPJTNvu6AlhSIWQ41mp-9XTfbDHWRBuHBKG-9efVJipEwqgFqr4DIkZOvPp4Ne6IIorHJjHrqw3Z5OVCfWb1gqgjTnl415naxMMrSby3dZ9_8qGRURx_1NdaTscA_lRf19gIrKVdTNeSsX78xJqqguIN3Djt5Wx6MtMCg7bCX-QdDuPdCeEENLFonw_MsTjTHAzx8_bxf6FwFAn6DmtQGVbvTROzptPpFNqC157rAW-Ux8ieQjMTIhH9c1cqOeZnuDzq1pO9T7dsMJUMXsckrDocJg3HqoUnO8gK87dpiEnn-zxDK0iIJbcgoZNHBEwwnASBrgXtMokg8DxqtzZz4ukdge4xEFh8bF480MIwCAYO14ZmKyJ_y20aYvXcgXtqjegOf_FN_IOKJUzkbcUD6g_i_Bps1LR7iVfqOBoBzeWAyyGPm8Pdelb9XPfaaUX0fEbG5G1HvK9KcfnvP_oQ83x-8-mdnof78x1WRI0JVHlc3eo_JVbqcBXpw21l3FTC8GibfTo5FfbkxlOOQuxTNq_8fUY0GE1Un1OrA3oxhQG20x0ZU8Vl1LZtVFdkHIxhZBSi9aRDGfBS1Taj81cAFVM4aRHKB1L9iKKtkuVpv-htLlM63yyaZqrynQ99s2JnQLe002JIM6YgWVOGCHYoZpfwonY0tYtcCGPtF8_0W0KAsb0WIvNvQrcPcObSxQAvRXfN_TDonSSlpiHceyZqrx5u1UeY5G3wUk6NtaB1OOuD25W0vtvYV2D0EXlxd6afoasw
GET {{Restaurants.API_HostAddress}}/api/restaurants
Authorization: Bearer {{token}}
###

GET {{Restaurants.API_HostAddress}}/api/restaurants?searchPhrase=&pageSize=5&pageNumber=1
Authorization: Bearer {{token}}
  
###

GET {{Restaurants.API_HostAddress}}/api/restaurants?searchPhrase=&pageSize=5&pageNumber=1&sortBy=Name&sortDirection=Descending
Authorization: Bearer {{token}}

###

GET {{Restaurants.API_HostAddress}}/api/restaurants/2

###
POST {{Restaurants.API_HostAddress}}/api/restaurants
Content-Type: application/json
Authorization: Bearer {{tokenOwner}}

{
  "Name": "Test Delights",
  "Description": "A Sweet experience like no other",
  "Category": "Italian",
  "HasDelivery": true,
  "ContactEmail": "sweet@gourmetdelights.com",
  "ContactNumber": "555-123-4567",
  "City": "Metropolis",
  "Street": "456 Gourmet Avenue",
  "PostalCode": "54-654"
}

###

DELETE {{Restaurants.API_HostAddress}}/api/restaurants/4

###

PATCH {{Restaurants.API_HostAddress}}/api/restaurants/3
Content-Type: application/json

{
  "Name": "Rest Delights",
  "Description": "A Sweet experience like no other",
  "Category": "Italian"
}

###

POST {{Restaurants.API_HostAddress}}/api/restaurant/3/dishes
Content-Type: application/json

{
 "Name": "Sample Dish",
 "Description": "Sample Description",
 "Price": "1"
}

###

GET {{Restaurants.API_HostAddress}}/api/restaurant/1/dishes
Authorization: Bearer {{token}}
###

GET {{Restaurants.API_HostAddress}}/api/restaurant/3/dishes/4

###

DELETE {{Restaurants.API_HostAddress}}/api/restaurant/3/dishes

###
POST {{Restaurants.API_HostAddress}}/api/identity/register
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "Password1!"
}

### 

POST {{Restaurants.API_HostAddress}}/api/identity/login
Content-Type: application/json

{
  "email": "owner@test.com",
  "password": "Password1!"
}

###

POST {{Restaurants.API_HostAddress}}/api/identity/login
Content-Type: application/json

{
  "email": "owner@test.com",
  "password": "Password1!"
}

###

POST {{Restaurants.API_HostAddress}}/api/identity/register
Content-Type: application/json

{
  "email": "owner@test.com",
  "password": "Password1!"
}

### 

POST {{Restaurants.API_HostAddress}}/api/identity/userRole
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "UserEmail": "user@test.com",
  "RoleName": "User"
}

###

PATCH {{Restaurants.API_HostAddress}}/api/identity/user
Content-Type: application/json
Authorization: Bearer {{tokenOwner}}

{
  "DateOfBirth": "1996-11-10",
  "Nationality": "German"
}

###