@host = https://localhost
@port = 7149
@Restaurants.API_HostAddress = https://localhost:7149
@token = CfDJ8DFRKF6ibBBCqWm4AJ29De-EAzjHWGsmudhkG_p4f-7eFNlp-8rq3uSrYOz7JK_suZS0VjD3JUv2lulNo4XQlrVzzwW1ZjJ9SPJWqcnOVmNWmJwAs31fdLc-cu6vRCEPCsHWLlTOATMV4fL0GRDmt5Mu6Vgt52c9rr_nBynuo41x8hFcDXb0_Qc_zyNEY9H83TI7ZWHXI7zuztMaw2AqRBPpLKMSx_DNQLiNK7RLy_qY2e3eH0cTnCT6WIpTKE3pOHPuQ0svBVUAEWe_7NU87qJ-Z8YmEEx-wMBXCCYCGsTb8q7fDFUkQ0h4NiI4ZarVil1zY1pikjWibgaXmCdmkiFbxzSbEYoE8ppZT-p9mhMV_wcnQtrNj39lREQVFHGHlDT1km_QgwJwxdyT3lT489WLKxajs1iOOydapRW8bt8XHLFUV_pYECT8wsLLTTHmaBgiKTMLAOrUPw_jxcuQLkv7VudYA0MVGxo7xHoXJLM3w8vnm_rGPH9vFrWJMxxiBA1SQ5Sx_1siGL_TlKKULd7rIVKVzRYq_bMIKQMJQf5h4uod04Wr0ttbuVxDr_XZ3_B0Z6GMIXwWte85d5xkkt-KEPlkPCll5xI6jcrEpFGE4Uy461HYIqugFjGsgQusypKD1ybPE6uP4nctYoCaba9855WzR47YFh9SWU6bf53R80Mm6hlC3JzzBdYTu00kK7VTV-SzV_NGEst42VNGgmYdGbTXHRhWciJFAaavfy9XdmxuV-6coSMFcNzMYHsMBusWpB7sbHGc6wT2U2Qd3GZY_VHdwcQ-HFOG-IncJC1e

GET {{Restaurants.API_HostAddress}}/api/restaurants
Authorization: Bearer {{token}}
###

GET {{Restaurants.API_HostAddress}}/api/restaurants/2

###
POST {{Restaurants.API_HostAddress}}/api/restaurants
Content-Type: application/json

{
  "Name": "Sweet Delights",
  "Description": "A Sweet experience like no other",
  "Category": "Italian",
  "HasDelivery": true,
  "ContactEmail": "sweet@gourmetdelights.com",
  "ContactNumber": "555-123-4567",
  "City": "Metropolis",
  "Street": "456 Gourmet Avenue",
  "PostalCode": "54-654"
}

###

DELETE {{Restaurants.API_HostAddress}}/api/restaurants/4

###

PATCH {{Restaurants.API_HostAddress}}/api/restaurants/3
Content-Type: application/json

{
  "Name": "Rest Delights",
  "Description": "A Sweet experience like no other",
  "Category": "Italian"
}

###

POST {{Restaurants.API_HostAddress}}/api/restaurant/3/dishes
Content-Type: application/json

{
 "Name": "Sample Dish",
 "Description": "Sample Description",
 "Price": "1"
}

###

GET {{Restaurants.API_HostAddress}}/api/restaurant/3/dishes

###

GET {{Restaurants.API_HostAddress}}/api/restaurant/3/dishes/4

###

DELETE {{Restaurants.API_HostAddress}}/api/restaurant/3/dishes

###
POST {{Restaurants.API_HostAddress}}/api/identity/register
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "Password1!"
}

### 

POST {{Restaurants.API_HostAddress}}/api/identity/login
Content-Type: application/json

{
  "email": "admin@test.com",
  "password": "Password1!"
}

###

POST {{Restaurants.API_HostAddress}}/api/identity/register
Content-Type: application/json

{
  "email": "owner@test.com",
  "password": "Password1!"
}

### 

POST {{Restaurants.API_HostAddress}}/api/identity/userRole
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "UserEmail": "user@test.com",
  "RoleName": "User"
}

###
