@host = https://localhost
@port = 7149
@Restaurants.API_HostAddress = https://localhost:7149
@token = CfDJ8DFRKF6ibBBCqWm4AJ29De9WysvJkmX_eg40JSgBmBdRGo2oAPs38_hXW0sun9vn80HMOi0Lnb1PFPuljoVsjqTlSyBZbh6J_jKsKirNc_ztdX-OAQSlkopQLXAgmU6rwMOHfjBTwg1eYlVifh8dYJfIw7_fJn8sKcMHAjqPcqpJYduBLcu6dVe67I_uVbzBaR2Wbky8K3MLJePwEteTQRlDOVJ2y9JqY-0RXw3rMiKgjOsKal-Vgn6hwv05Pv0Ayop_dWs9w_8IEECm3Ghq8Y4g9taLkILVUFbhMbj90FNbTZIpgc8ofDLSL4IhbhbZzQOaJzgmiULQiXO0C2WqPHho2hTq3fWmhNntyXLYwxTAJUU1eNHnc__wZloZsspeyWP537m8XpwL4UUTq4ow5Ce5ipGamVZtSq2_1FC7DghDwSpFlzK9r7NWvF7tk0UuBN4Cp0MJz_cvem2GFSEOMPO5BrnIE2O29JMUdN9oyJC04gqUTZEm_eOu2fSSSzpPpDbQnaI4fKBRcbQ19qsGin_JfjFRQN8TcOLJNfCjFUOVnb8MIJm3AS1yn4rfNQzZGyH5xdn6RXWYomuhwYXM7-mwLi_V23ZFH89FwRRkhxawS0z6G9S5PqPDuN1yVipjsGps5Do54vmxtAtOOVYfXPzNjbPdpk7d5PPAlVq5_z9qGGqHt0AzZ2qWOh561GadteCKwJy-CCwX4awxX_7gbxIX0TyedmW7dF0l7jiBOnJ9xfSGvG9oxoHAIWY0gfHl-HSkLG6JnPqy__lX0ELKqrPv2s-WDN_mywzfsaZ9C4MlxXioS_a8svjL7v9XWvbcpDSjl8GI4SmnvKxW7EiYP9Lg8nFsmMtrOGeEYXxanUQW
@tokenOwner = CfDJ8DFRKF6ibBBCqWm4AJ29De_7oGUpHyGcLoxIBgdCgMjdU0JvVtQ8AiBvwE_juPP84QeCap0mHjashk-_pts0UEVrvHGeZuCsnYeOopUByeoGbOfrA87N9dx9dYvEaQo6Fy1U8BoLJdNf-aV4pEEqp_tHKiEKLWmn1gm31Ki56LQ39HQcJX0cIW4HBPxda33OYjPM2MlBv-YdetX6Bd4iXO1PcObyVFMHyUQydWVvfDH-ozZd_H58xH5VCJfhyJOYFntzW7PuWxT-KVe3stvmO3Lptkx28NHibV34kMM3jhh1d-2KBG0rM3_WZ8rBj9Oe_52mRpLF-c5zh9d8Mon0cuM2nxnjMcbvinDyaTw3uCmGPkb0kKw5vvCWJoAcmbUb06vcj-eojYa8ibsIv2Do5OqtRFTFP7N65Lk8iaevc0lEbmWLW54bOL2RzXK-u4OTUNLWcXttYFGKsvSvFKyIf_Zrez4vtBHzR4gIoTucZj9UVxENECiQPDyfdgV_Mrkkh0mW-mnudFXfGmdR8F31bGPiDnmzMxpIu-Lj497WS9xGdJCoWMlfXdk2aWf03qoaeML8ziqVZN6p8GNp7GuDUWptVHnTOhM8OVOoaDdncoAfiaawUxsHcXObmVeju1dTB4Jm84S8anTGqhYvMeY3FvEsJdRcI7lwwZbkS6CyvC0_zJMOfMcNGIaW-aMk8_dI0ErzN0WdHuqUFv6EcqAT43ZvblEysuTc_9aqQKteloLSqnahXHFt5dIeOKiYEgt2tUAOOnq4sQx3bya3A_dPQ8Rh-m5G3YTR-RCNgTUGSX6J6T09psZAPCNYdc-GGtvblwsT3TElEbo-JVGAGf5ZjKjPiuDJy04-UHFZVBqUdK54JP89fRlP9_mikmhj03A7cQ
GET {{Restaurants.API_HostAddress}}/api/restaurants
Authorization: Bearer {{token}}
###

GET {{Restaurants.API_HostAddress}}/api/restaurants?searchPhrase=&pageSize=5&pageNumber=1
Authorization: Bearer {{token}}
  
###

GET {{Restaurants.API_HostAddress}}/api/restaurants?searchPhrase=&pageSize=5&pageNumber=1&sortBy=Name&sortDirection=Descending
Authorization: Bearer {{token}}

###

GET {{Restaurants.API_HostAddress}}/api/restaurants/2

###
POST {{Restaurants.API_HostAddress}}/api/restaurants
Content-Type: application/json
Authorization: Bearer {{tokenOwner}}

{
  "Name": "Test Delights",
  "Description": "A Sweet experience like no other",
  "Category": "Italian",
  "HasDelivery": true,
  "ContactEmail": "sweet@gourmetdelights.com",
  "ContactNumber": "555-123-4567",
  "City": "Metropolis",
  "Street": "456 Gourmet Avenue",
  "PostalCode": "54-654"
}

###

DELETE {{Restaurants.API_HostAddress}}/api/restaurants/5
Authorization: Bearer {{token}}
###

PATCH {{Restaurants.API_HostAddress}}/api/restaurants/3
Content-Type: application/json

{
  "Name": "Rest Delights",
  "Description": "A Sweet experience like no other",
  "Category": "Italian"
}

###

POST {{Restaurants.API_HostAddress}}/api/restaurant/3/dishes
Content-Type: application/json

{
 "Name": "Sample Dish",
 "Description": "Sample Description",
 "Price": "1"
}

###

GET {{Restaurants.API_HostAddress}}/api/restaurant/1/dishes
Authorization: Bearer {{token}}
###

GET {{Restaurants.API_HostAddress}}/api/restaurant/3/dishes/4

###

DELETE {{Restaurants.API_HostAddress}}/api/restaurant/3/dishes

###
POST {{Restaurants.API_HostAddress}}/api/identity/register
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "Password1!"
}

### 

POST {{Restaurants.API_HostAddress}}/api/identity/login
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "Password1!"
}

###

POST {{Restaurants.API_HostAddress}}/api/identity/login
Content-Type: application/json

{
  "email": "owner@test.com",
  "password": "Password1!"
}

###

POST {{Restaurants.API_HostAddress}}/api/identity/register
Content-Type: application/json

{
  "email": "owner@test.com",
  "password": "Password1!"
}

### 

POST {{Restaurants.API_HostAddress}}/api/identity/userRole
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "UserEmail": "user@test.com",
  "RoleName": "User"
}

###

PATCH {{Restaurants.API_HostAddress}}/api/identity/user
Content-Type: application/json
Authorization: Bearer {{tokenOwner}}

{
  "DateOfBirth": "1996-11-10",
  "Nationality": "German"
}

###